name: Go Code Test Workflow
on: [push]

jobs:
  test:

    strategy:
      matrix:
        go-version: [1.16.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    # Service containers to run with `runner-job`
    services:
        # Label used to access the service container
        rabbit:
          # Docker Hub image
          image: rabbitmq:3-management-alpine
          #
          ports:
            # Opens tcp port 6379 on the host and service container
            - 5672:5672
            - 15672:15672
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./... -v

